In [1]:
import numpy as np

1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [7]:
a = np.zeros((8, 8))
np.pad(a, 1, constant_values = 1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [36]:
np.fromfunction(lambda x, y: (x + y + 1) % 2, (8, 8))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули.

In [99]:
np.diag([1, 2, 3, 4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее вдоль каждой строки было равно нулю.

In [78]:
a = np.random.random((5, 5))
a - np.transpose(np.mean(a, 1) + np.zeros((5, 5)))

array([[-0.16502618,  0.03036709, -0.04977935, -0.02400938,  0.20844782],
       [ 0.46903347, -0.21629752, -0.34060356, -0.4471884 ,  0.53505601],
       [-0.3795065 ,  0.32003358,  0.02619773,  0.2753919 , -0.24211671],
       [-0.05803554,  0.1283059 ,  0.33060084, -0.06266519, -0.33820601],
       [ 0.39159897, -0.09234081, -0.13547468, -0.36953731,  0.20575383]])

5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [175]:
a = np.random.random((10, 3))
a[np.arange(10), np.abs(a - 0.5).argmin(1)]

array([0.5053714 , 0.43381311, 0.34028335, 0.47744654, 0.76351075,
       0.62630992, 0.27867449, 0.33458496, 0.33647866, 0.60911841])

6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [109]:
a = np.random.random((6, 6))
np.sum(a, 1) / np.max(a, 0)

array([7.76133332, 3.09083515, 3.4467215 , 3.77534101, 4.29143633,
       4.18042848])

7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [127]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
np.max(x[np.delete(np.argwhere(x == 0) + 1, np.where(np.argwhere(x == 0) + 1 == 9))])

np.int64(5)

8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [145]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x + np.array([np.size(i[i == j]) for j in range(10)])

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

9. Задайте два массива a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]]) и b = np.array([3, 5, 10, 0]). Создайте массив, в котором каждый элемент первого массива заменен на ближайший к нему элемент второго массива.

In [158]:
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]])
b = np.array([3, 5, 10, 0])
np.array([b[np.argmin(np.abs(b - a.reshape(9)[i]))] for i in range(9)]).reshape(3, 3)

array([[ 0,  5,  3],
       [ 5,  5, 10],
       [ 3,  5,  0]])

10. Найдите скользящие средние с окном размера 3 по массиву a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2]).

In [164]:
a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2])
np.convolve(a, np.ones(3) / 3, mode = 'valid')

array([2.76666667, 4.8       , 5.5       , 7.96666667, 6.26666667,
       2.26666667, 0.53333333, 0.26666667])

Задача со звездочкой.

Создайте произвольный двумерный массив NxM, N, M > 1. На его основе создайте новый двумерный массив, значения в котором являются средним значением исходного во всевозможных окошках размера 2х2 со сдвигом 1 по вертикали и горизонтали.

In [171]:
n, m = 4, 10
a = np.arange(n * m).reshape(n, m)
print("Input:\n", a, "\n\nOutput:")
(a[:-1, :-1] + a[:-1, 1:] + a[1:, :-1] + a[1:, 1:]) / 4

Input:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]] 

Output:


array([[ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5],
       [15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5],
       [25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5]])